<a href="https://colab.research.google.com/github/NikosKats/ColabFiles/blob/Udemy-Pytorch-1/Udemy_Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch 

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1024, 0.2805, 0.2435, 0.9774],
        [0.4139, 0.2811, 0.2295, 0.1047],
        [0.6149, 0.9982, 0.2227, 0.5411]])

In [9]:
random_tensor.ndim

2

In [11]:
random_image_size_tensor = torch.rand(size=(3,224,224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [12]:
torch.rand(3,3)

tensor([[0.1804, 0.4357, 0.9419],
        [0.7316, 0.8788, 0.6979],
        [0.0193, 0.0926, 0.9450]])

In [14]:
zeros = torch.zeros(3, 4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

In [17]:
random_tensor.dtype

torch.float32

In [25]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], 
                               dtype=None,
                               device="cpu",
                               requires_grad=False
                               )
float_32_tensor


tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor